In [3]:
#import libraries
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [14]:
data = pd.read_csv('C:/Users/DEBASHISH THAKUR/Desktop/cnn dataset/mnist_train.csv')


In [15]:
data.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [19]:
#reshaping into 28x28 array
data.iloc[3,1:].values.reshape(28,28).astype('uint8')

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0, 124, 253, 255,  63,   0,   0,   0,   0,
          0,   0],
       [  

In [20]:
#preprocessing data
#storing pixel array in form length width and channel in df_x
df_x = data.iloc[:,1:].values.reshape(len(data),28, 28, 1)

#storing the labels in y
y = data.iloc[:,0].values

In [21]:
#converting labels to categorical figures

df_y = keras.utils.to_categorical(y,num_classes=10)

In [22]:
df_x = np.array(df_x)
df_y = np.array(df_y)

In [23]:
#labels 
y

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [24]:
df_y

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [25]:
#test_train_split
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.2, random_state = 4)

In [28]:
#CNN model
model = Sequential()
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adadelta', metrics = ['accuracy'])

In [31]:
#fitting it with 100 images for testing
model.fit(x_train, y_train, epochs = 10, validation_data = (x_test, y_test))

Train on 48000 samples, validate on 12000 samples
Epoch 1/10
48000/48000 [==============================] - 39s 806us/step - loss: 0.1202 - accuracy: 0.9645 - val_loss: 0.0902 - val_accuracy: 0.9726
Epoch 2/10
48000/48000 [==============================] - 42s 873us/step - loss: 0.0923 - accuracy: 0.9726 - val_loss: 0.1075 - val_accuracy: 0.9730
Epoch 3/10
48000/48000 [==============================] - 42s 878us/step - loss: 0.0824 - accuracy: 0.9768 - val_loss: 0.1040 - val_accuracy: 0.9711
Epoch 4/10
48000/48000 [==============================] - 41s 858us/step - loss: 0.0756 - accuracy: 0.9782 - val_loss: 0.0925 - val_accuracy: 0.9765
Epoch 5/10
48000/48000 [==============================] - 41s 861us/step - loss: 0.0677 - accuracy: 0.9809 - val_loss: 0.1011 - val_accuracy: 0.9770
Epoch 6/10
48000/48000 [==============================] - 41s 844us/step - loss: 0.0627 - accuracy: 0.9829 - val_loss: 0.0987 - val_accuracy: 0.9750
Epoch 7/10
48000/48000 [==============================] 